server:
  port: 8082
  forward-headers-strategy: framework
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/tweetsdb}

springdoc:
  version: '@springdoc.version@'