server:
  port: 8082
  forward-headers-strategy: framework

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/tweetsdb}

springdoc:
  version: '@springdoc.version@'