server:
  port: 8082
  forward-headers-strategy: framework
spring:
  # MongoDB
  data:
    mongodb:
      host: localhost
      database: dataSource
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.11

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true